steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: "PULL"
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/${_APP_NAME}:${_ENVIRONMENT} || exit 0']

  - name: "golang:1.17"
    id: "TEST"
    entrypoint: '/bin/bash -c'
    args: ['go', 'test', '-v', './api']
    env:
      - 'GO111MODULE=on'

  - name: 'gcr.io/cloud-builders/docker'
    id: "BUILD"
    args:
        [
          'build',
          '-t',
          'gcr.io/$PROJECT_ID/${_APP_NAME}:${_ENVIRONMENT}',
          '--cache-from',
          'gcr.io/$PROJECT_ID/${_APP_NAME}:${_ENVIRONMENT}',
          '.',
        ]

  - name: 'gcr.io/cloud-builders/docker'
    id: "PUSH"
    args: ['push', 'gcr.io/$PROJECT_ID/${_APP_NAME}:${_ENVIRONMENT}']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: "DEPLOY"
    args:
      [
        'run',
        'deploy',
        '${_ENVIRONMENT}-dar-integration-sandbox',
        '--image',
        'gcr.io/$PROJECT_ID/${_APP_NAME}:${_ENVIRONMENT}',
        '--platform',
        'managed',
        '--region',
        '${_REGION}',
        '--allow-unauthenticated',
      ]

timeout: 2400s
  